"""YOLO defaults for component detection and scratch segmentation."""

from configs.path import DATA_DIR, MODELS_DIR, OUTPUTS_DIR


"""Component detector dataset"""
YOLO_COMPONENT_DATASET_DIR = DATA_DIR / "component"
YOLO_COMPONENT_TRAIN_DATA = YOLO_COMPONENT_DATASET_DIR / "data.yaml"
YOLO_COMPONENT_CLASS_NAMES = ["component"]
YOLO_COMPONENT_NUM_CLASSES = len(YOLO_COMPONENT_CLASS_NAMES)

"""Component detector model"""
YOLO_COMPONENT_MODEL_VERSION = 1
YOLO_COMPONENT_BASE_MODEL = "yolo26n.pt"
YOLO_COMPONENT_TRAIN_PROJECT = MODELS_DIR / "yolo"
YOLO_COMPONENT_RUN_NAME = "component"
YOLO_COMPONENT_RUNS_DIR = YOLO_COMPONENT_TRAIN_PROJECT / YOLO_COMPONENT_RUN_NAME
YOLO_COMPONENT_MODEL = YOLO_COMPONENT_RUNS_DIR / "weights" / "best.pt"
YOLO_COMPONENT_TASK = "detect"

"""Component detector training"""
YOLO_COMPONENT_IMAGE_SIZE = 640
YOLO_COMPONENT_EPOCHS = 100
YOLO_COMPONENT_BATCH_SIZE = 8
YOLO_COMPONENT_PATIENCE = 20
YOLO_COMPONENT_LEARNING_RATE = 0.01
YOLO_COMPONENT_WORKERS = 2
YOLO_COMPONENT_DEVICE = None
YOLO_COMPONENT_SEED = 42
YOLO_COMPONENT_EXIST_OK = True

"""Component detector inference"""
YOLO_COMPONENT_CONFIDENCE_THRESHOLD = 0.25
YOLO_COMPONENT_IOU_THRESHOLD = 0.70
YOLO_COMPONENT_DEFAULT_IMAGE = YOLO_COMPONENT_DATASET_DIR / "valid" / "images"
YOLO_COMPONENT_INFERENCE_OUTPUT = OUTPUTS_DIR / "yolo" / "component"

"""Component detector evaluation"""
YOLO_COMPONENT_METRICS_OUTPUT = OUTPUTS_DIR / "metrics" / "yolo_component"


"""Scratch segmentation dataset"""
YOLO_SCRATCH_DATASET_DIR = DATA_DIR / "scratch_yolo_seg"
YOLO_SCRATCH_TRAIN_DATA = YOLO_SCRATCH_DATASET_DIR / "data.yaml"
YOLO_SCRATCH_EVAL_DATASET = DATA_DIR / "scratch_patches"
YOLO_SCRATCH_CLASS_NAMES = ["scratch"]
YOLO_SCRATCH_NUM_CLASSES = len(YOLO_SCRATCH_CLASS_NAMES)

"""Scratch segmentation model"""
YOLO_SCRATCH_MODEL_VERSION = "26n"
YOLO_SCRATCH_BASE_MODEL = "yolo26n-seg.pt"
YOLO_SCRATCH_TRAIN_PROJECT = MODELS_DIR / "yolo"
YOLO_SCRATCH_RUN_NAME = "scratch_seg"
YOLO_SCRATCH_MODEL_VARIANTS = {
    "26n": MODELS_DIR / "yolo" / "scratch_yolo26n_seg" / "weights" / "best.pt",
    "26s": MODELS_DIR / "yolo" / "scratch_yolo26s_seg" / "weights" / "best.pt",
}
YOLO_SCRATCH_MODEL = YOLO_SCRATCH_MODEL_VARIANTS[YOLO_SCRATCH_MODEL_VERSION]
YOLO_SCRATCH_TASK = "segment"

"""Scratch segmentation training"""
YOLO_SCRATCH_IMAGE_SIZE = 512
YOLO_SCRATCH_EPOCHS = 100
YOLO_SCRATCH_BATCH_SIZE = 16
YOLO_SCRATCH_PATIENCE = 30
YOLO_SCRATCH_LEARNING_RATE = 0.002
YOLO_SCRATCH_WORKERS = 2
YOLO_SCRATCH_DEVICE = None
YOLO_SCRATCH_SEED = 42
YOLO_SCRATCH_EXIST_OK = True

"""Scratch segmentation inference"""
YOLO_SCRATCH_CONFIDENCE_THRESHOLD = 0.10
YOLO_SCRATCH_IOU_THRESHOLD = 0.70
YOLO_SCRATCH_MASK_THRESHOLD = 0.50
YOLO_SCRATCH_TILE_SIZE = 512
YOLO_SCRATCH_TILE_OVERLAP = 0.15
YOLO_SCRATCH_OVERLAY_ALPHA = 0.25
YOLO_SCRATCH_DEFAULT_IMAGE = DATA_DIR / "raw" / "Image_20260714164248809.bmp"
YOLO_SCRATCH_INFERENCE_OUTPUT = OUTPUTS_DIR / "yolo" / "scratch"

"""Scratch segmentation evaluation"""
YOLO_SCRATCH_METRICS_OUTPUT = OUTPUTS_DIR / "metrics" / "yolo_scratch"


"""Backward-compatible component aliases."""
YOLO_DATASET_DIR = YOLO_COMPONENT_DATASET_DIR
YOLO_TRAIN_DATA = YOLO_COMPONENT_TRAIN_DATA
YOLO_CLASS_NAMES = YOLO_COMPONENT_CLASS_NAMES
YOLO_NUM_CLASSES = YOLO_COMPONENT_NUM_CLASSES
YOLO_MODEL_VERSION = YOLO_COMPONENT_MODEL_VERSION
YOLO_BASE_MODEL = YOLO_COMPONENT_BASE_MODEL
YOLO_TRAIN_PROJECT = YOLO_COMPONENT_TRAIN_PROJECT
YOLO_RUN_NAME = YOLO_COMPONENT_RUN_NAME
YOLO_RUNS_DIR = YOLO_COMPONENT_RUNS_DIR
YOLO_MODEL = YOLO_COMPONENT_MODEL
YOLO_TASK = YOLO_COMPONENT_TASK
YOLO_IMAGE_SIZE = YOLO_COMPONENT_IMAGE_SIZE
YOLO_EPOCHS = YOLO_COMPONENT_EPOCHS
YOLO_BATCH_SIZE = YOLO_COMPONENT_BATCH_SIZE
YOLO_PATIENCE = YOLO_COMPONENT_PATIENCE
YOLO_LEARNING_RATE = YOLO_COMPONENT_LEARNING_RATE
YOLO_WORKERS = YOLO_COMPONENT_WORKERS
YOLO_DEVICE = YOLO_COMPONENT_DEVICE
YOLO_SEED = YOLO_COMPONENT_SEED
YOLO_EXIST_OK = YOLO_COMPONENT_EXIST_OK
YOLO_CONFIDENCE_THRESHOLD = YOLO_COMPONENT_CONFIDENCE_THRESHOLD
YOLO_IOU_THRESHOLD = YOLO_COMPONENT_IOU_THRESHOLD
YOLO_DEFAULT_IMAGE = YOLO_COMPONENT_DEFAULT_IMAGE
YOLO_INFERENCE_OUTPUT = YOLO_COMPONENT_INFERENCE_OUTPUT
YOLO_METRICS_OUTPUT = YOLO_COMPONENT_METRICS_OUTPUT
